require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlayedHolesController do

  # This should return the minimal set of attributes required to create a valid
  # PlayedHole. As you add validations to PlayedHole, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlayedHolesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all played_holes as @played_holes" do
      played_hole = PlayedHole.create! valid_attributes
      get :index, {}, valid_session
      assigns(:played_holes).should eq([played_hole])
    end
  end

  describe "GET show" do
    it "assigns the requested played_hole as @played_hole" do
      played_hole = PlayedHole.create! valid_attributes
      get :show, {:id => played_hole.to_param}, valid_session
      assigns(:played_hole).should eq(played_hole)
    end
  end

  describe "GET new" do
    it "assigns a new played_hole as @played_hole" do
      get :new, {}, valid_session
      assigns(:played_hole).should be_a_new(PlayedHole)
    end
  end

  describe "GET edit" do
    it "assigns the requested played_hole as @played_hole" do
      played_hole = PlayedHole.create! valid_attributes
      get :edit, {:id => played_hole.to_param}, valid_session
      assigns(:played_hole).should eq(played_hole)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlayedHole" do
        expect {
          post :create, {:played_hole => valid_attributes}, valid_session
        }.to change(PlayedHole, :count).by(1)
      end

      it "assigns a newly created played_hole as @played_hole" do
        post :create, {:played_hole => valid_attributes}, valid_session
        assigns(:played_hole).should be_a(PlayedHole)
        assigns(:played_hole).should be_persisted
      end

      it "redirects to the created played_hole" do
        post :create, {:played_hole => valid_attributes}, valid_session
        response.should redirect_to(PlayedHole.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved played_hole as @played_hole" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlayedHole.any_instance.stub(:save).and_return(false)
        post :create, {:played_hole => {}}, valid_session
        assigns(:played_hole).should be_a_new(PlayedHole)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlayedHole.any_instance.stub(:save).and_return(false)
        post :create, {:played_hole => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested played_hole" do
        played_hole = PlayedHole.create! valid_attributes
        # Assuming there are no other played_holes in the database, this
        # specifies that the PlayedHole created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlayedHole.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => played_hole.to_param, :played_hole => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested played_hole as @played_hole" do
        played_hole = PlayedHole.create! valid_attributes
        put :update, {:id => played_hole.to_param, :played_hole => valid_attributes}, valid_session
        assigns(:played_hole).should eq(played_hole)
      end

      it "redirects to the played_hole" do
        played_hole = PlayedHole.create! valid_attributes
        put :update, {:id => played_hole.to_param, :played_hole => valid_attributes}, valid_session
        response.should redirect_to(played_hole)
      end
    end

    describe "with invalid params" do
      it "assigns the played_hole as @played_hole" do
        played_hole = PlayedHole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlayedHole.any_instance.stub(:save).and_return(false)
        put :update, {:id => played_hole.to_param, :played_hole => {}}, valid_session
        assigns(:played_hole).should eq(played_hole)
      end

      it "re-renders the 'edit' template" do
        played_hole = PlayedHole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlayedHole.any_instance.stub(:save).and_return(false)
        put :update, {:id => played_hole.to_param, :played_hole => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested played_hole" do
      played_hole = PlayedHole.create! valid_attributes
      expect {
        delete :destroy, {:id => played_hole.to_param}, valid_session
      }.to change(PlayedHole, :count).by(-1)
    end

    it "redirects to the played_holes list" do
      played_hole = PlayedHole.create! valid_attributes
      delete :destroy, {:id => played_hole.to_param}, valid_session
      response.should redirect_to(played_holes_url)
    end
  end

end
